// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Person;
@class Person_PhoneNumber;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Person_PhoneType

typedef GPB_ENUM(Person_PhoneType) {
  Person_PhoneType_Mobile = 0,
  Person_PhoneType_Home = 1,
  Person_PhoneType_Work = 2,
};

GPBEnumDescriptor *Person_PhoneType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Person_PhoneType_IsValidValue(int32_t value);

#pragma mark - AddressbookRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface AddressbookRoot : GPBRootObject
@end

#pragma mark - Person

typedef GPB_ENUM(Person_FieldNumber) {
  Person_FieldNumber_Name = 1,
  Person_FieldNumber_Id_p = 2,
  Person_FieldNumber_Email = 3,
  Person_FieldNumber_PhonesArray = 4,
};

@interface Person : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@property(nonatomic, readwrite) int32_t id_p;

@property(nonatomic, readwrite) BOOL hasId_p;
@property(nonatomic, readwrite, copy, null_resettable) NSString *email;
/** Test to see if @c email has been set. */
@property(nonatomic, readwrite) BOOL hasEmail;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Person_PhoneNumber*> *phonesArray;
/** The number of items in @c phonesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger phonesArray_Count;

@end

#pragma mark - Person_PhoneNumber

typedef GPB_ENUM(Person_PhoneNumber_FieldNumber) {
  Person_PhoneNumber_FieldNumber_Number = 1,
  Person_PhoneNumber_FieldNumber_Type = 2,
};

@interface Person_PhoneNumber : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *number;
/** Test to see if @c number has been set. */
@property(nonatomic, readwrite) BOOL hasNumber;

@property(nonatomic, readwrite) Person_PhoneType type;

@property(nonatomic, readwrite) BOOL hasType;
@end

#pragma mark - AddressBook

typedef GPB_ENUM(AddressBook_FieldNumber) {
  AddressBook_FieldNumber_PeopleArray = 1,
};

@interface AddressBook : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Person*> *peopleArray;
/** The number of items in @c peopleArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger peopleArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
