# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def memoize(func):
    func.memo = {1: 1, 2: 1}
    return func


@memoize
def fib(n):
    if n == 0:
        return 0
    for i in range(3, n+1):
        fib.memo[i] = fib.memo[i-1] + fib.memo[i-2]
    return fib.memo[n]


def calculate(maxvalue):
    result = 0
    index = 1
    while True:
        value = fib(index)
        if value > maxvalue:
            return result
        if value % 2 == 0:
            result += value
        index += 1


res = calculate(4000000)
print res
